"""ajuste em funcionario e dias trabalho-

Revision ID: 27f508c3385f
Revises: db8778d88899
Create Date: 2026-01-19 20:59:06.214061

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '27f508c3385f'
down_revision = 'db8778d88899'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dias_trabalho', schema=None) as batch_op:
        batch_op.alter_column('minutos_trabalhados',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('minutos_previstos',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intervalo_obrigatorio', sa.Boolean(), nullable=False))
        batch_op.drop_column('intervalo_obrigatorio_min')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('intervalo_obrigatorio_min', sa.BOOLEAN(), nullable=False))
        batch_op.drop_column('intervalo_obrigatorio')

    with op.batch_alter_table('dias_trabalho', schema=None) as batch_op:
        batch_op.alter_column('minutos_previstos',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('minutos_trabalhados',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
