"""cria tabela correcoes_ponto

Revision ID: 2d52e9b242fb
Revises: 3e1996aa294c
Create Date: 2026-01-20 19:25:07.491689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2d52e9b242fb'
down_revision = '3e1996aa294c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('correcoes_ponto',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ponto_id', sa.Integer(), nullable=False),
    sa.Column('admin_id', sa.Integer(), nullable=False),
    sa.Column('antes', sa.Text(), nullable=False),
    sa.Column('depois', sa.Text(), nullable=False),
    sa.Column('motivo', sa.String(length=25), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['admin_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['ponto_id'], ['pontos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('correcoes_ponto', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_correcoes_ponto_admin_id'), ['admin_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_correcoes_ponto_ponto_id'), ['ponto_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('correcoes_ponto', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_correcoes_ponto_ponto_id'))
        batch_op.drop_index(batch_op.f('ix_correcoes_ponto_admin_id'))

    op.drop_table('correcoes_ponto')
    # ### end Alembic commands ###
