"""ajuste em nullable em minutos_previstos e sald em dias trabalho-

Revision ID: 3e1996aa294c
Revises: 27f508c3385f
Create Date: 2026-01-19 21:02:47.876490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e1996aa294c'
down_revision = '27f508c3385f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dias_trabalho', schema=None) as batch_op:
        batch_op.alter_column('minutos_previstos',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('saldo_minutos',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('dias_trabalho', schema=None) as batch_op:
        batch_op.alter_column('saldo_minutos',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('minutos_previstos',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###
