"""cria tabela funcionarios

Revision ID: 8ae2c4afab70
Revises: 05e8184d8295
Create Date: 2026-01-16 20:15:06.286583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ae2c4afab70'
down_revision = '05e8184d8295'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('funcionarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(length=80), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('carga_diaria_min', sa.Integer(), nullable=False),
    sa.Column('carga_mensal_min', sa.Integer(), nullable=False),
    sa.Column('intervalo_obrigatorio_min', sa.Boolean(), nullable=False),
    sa.Column('criaado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('funcionarios')
    # ### end Alembic commands ###
