"""cria tabela pontos

Revision ID: a7c52e9201b4
Revises: 8ae2c4afab70
Create Date: 2026-01-17 14:52:35.127679

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7c52e9201b4'
down_revision = '8ae2c4afab70'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pontos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=30), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('hora', sa.Time(), nullable=False),
    sa.Column('origem', sa.String(length=20), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funcionario_id', 'data', 'tipo', name='uq_funcionario_data_tipo')
    )
    with op.batch_alter_table('pontos', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pontos_funcionario_id'), ['funcionario_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pontos', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pontos_funcionario_id'))

    op.drop_table('pontos')
    # ### end Alembic commands ###
