"""remove carga_mensal_min de funcionarios

Revision ID: ae3bacb34f18
Revises: 2d52e9b242fb
Create Date: 2026-02-23 07:12:52.990791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ae3bacb34f18'
down_revision = '2d52e9b242fb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.drop_column('carga_mensal_min')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('carga_mensal_min', sa.INTEGER(), nullable=False))

    # ### end Alembic commands ###
