"""cria tabela dias_trabalho

Revision ID: db8778d88899
Revises: a7c52e9201b4
Create Date: 2026-01-19 20:47:13.719580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db8778d88899'
down_revision = 'a7c52e9201b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dias_trabalho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('funcionario_id', sa.Integer(), nullable=False),
    sa.Column('data', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('minutos_trabalhados', sa.Integer(), nullable=False),
    sa.Column('minutos_previstos', sa.Integer(), nullable=False),
    sa.Column('saldo_minutos', sa.Integer(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['funcionario_id'], ['funcionarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('funcionario_id', 'data', name='uq_diatrabalho_funcionario_data')
    )
    with op.batch_alter_table('dias_trabalho', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dias_trabalho_funcionario_id'), ['funcionario_id'], unique=False)

    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criado_em', sa.DateTime(), nullable=False))
        batch_op.drop_column('criaado_em')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('funcionarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('criaado_em', sa.DATETIME(), nullable=False))
        batch_op.drop_column('criado_em')

    with op.batch_alter_table('dias_trabalho', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dias_trabalho_funcionario_id'))

    op.drop_table('dias_trabalho')
    # ### end Alembic commands ###
